import '@/components/Menu/Menu'
import '@/components/Board/Board'
import '@/components/Game/Game'
import '@/components/GameTile/GameTile'
import '@/components/GlobalShortcutsProvider/GlobalShortcutsProvider'
import '@/components/Ranking/Ranking'
import '@/components/HighestScore/HighestScore'